### ISSUE TITLE
Set App insights operation name

### ISSUE THREAD

**Issue by AndreasRo** [adrianmo/jmeter-backend-azure#10]
I would like to have the option to set Operation Name, or maybe have the Operation name set to the same value as Name. This will make it easier to separate between the different operations. 
![ghostoperations](https://user-images.githubusercontent.com/6039030/85133628-578e9c80-b23b-11ea-8056-8ca23c0d9d43.png)
Currently the Operatons list under Performance/Failures in AI only contains 'ghost' operations.

**Comment by adrianmo** [comment]
Hey @AndreasRo, thanks a lot for reporting it. I'll look into it in the coming days and update this thread.

**Comment by adrianmo** [comment]
Hey @AndreasRo, I've updated the plugin to set the Operation Name to the value of the test name. Please update to version 0.2.3 and give a try!

![image](https://user-images.githubusercontent.com/3786750/88075026-84a2d780-cb78-11ea-95bb-21511e2d3219.png)
