### ISSUE TITLE
Add adittional data to azure logs

### ISSUE THREAD

**Issue by mpanichella** [adrianmo/jmeter-backend-azure#11]
Hi!, very very good job. I want to add extra data, for example, environment (UAT, Production, etc) or others data. Its possible to add new field, for example, json field, to create other dimension in log, with my custom data?

**Comment by gabrielstar** [comment]
if it is only data like ENV then I modify testName e.g. jmeter-${ENV}-${TEST_VARIANT}
![image](https://user-images.githubusercontent.com/38763186/87299277-0016e000-c50c-11ea-8940-87e3853d6154.png)

Then you can use Kusto to filter by.

**Comment by mpanichella** [comment]
@gabrielstar thank you for your response, yes i do this, but i want to add more properties, bit create all from name, is a complex to create good metrics, for this reason i want to can create a customDimension with all property that i want. Thanks

**Comment by adrianmo** [comment]
Hey @mpanichella, thanks for using the plugin! I've updated it to allow users to set custom test properties that are added to the customDimension in App Insights. To add a custom property, make sure to set the `ai.` prefix, for example, you can add a property called `ai.environment` and set the value to whatever you want (UAT, Production, etc.). You can add as many custom properties as you want. 

Please update to version 0.2.3 and give it a try!

**Comment by mpanichella** [comment]
EXCELENT!!!!!!!!!!!!!!! thank you!!!!!
