### ISSUE TITLE
Integrate azure backend listener plugin in Java project

### ISSUE THREAD

**Issue by mjmadhu** [adrianmo/jmeter-backend-azure#16]
We want to add this jar as a project dependency to automate the addition of azure backend listener in a provided JMeter test plan (.jmx file). It would be good to have it hosted in a central repository.

**Comment by adrianmo** [comment]
@mjmadhu I've automated the publishing of new artifacts and also uploaded the current release (0.2.3) to Maven Central. You should now be able to integrate it in your Java project via pom, gradle, or others. Thank you!

https://search.maven.org/artifact/io.github.adrianmo/jmeter.backendlistener.azure
