### ISSUE TITLE
Missing default instrumentation key

### ISSUE THREAD

**Issue by josegoose** [adrianmo/jmeter-backend-azure#9]
Hi, I realized that it is missing the default instrumentation key.

`config.setInstrumentationKey(context.getParameter(KEY_INSTRUMENTATION_KEY, DEFAULT_INSTRUMENTATION_KEY));`

[In line 107](https://github.com/adrianmo/jmeter-backend-azure/blob/master/src/main/java/io/github/adrianmo/jmeter/backendlistener/azure/AzureBackendClient.java#L107)

**Comment by adrianmo** [comment]
Hi @josegoose, thanks for reaching out, the instrumentation key is not supposed to have a default value.  A unique instrumentation key is generated when a user creates an Application Insights resource. Therefore, I can't provide a default value. Thank you!
